In [1]:
import torch

In [2]:
grad_tensor = torch.zeros(3)

In [9]:
grad_tensor.requires_grad = True

In [10]:
grad_tensor

tensor([0., 0., 0.], requires_grad=True)

In [11]:
no_grad_tensor = torch.zeros(3)

In [12]:
no_grad_tensor

tensor([0., 0., 0.])

In [14]:
torch.cat((grad_tensor, no_grad_tensor))

tensor([0., 0., 0., 0., 0., 0.], grad_fn=<CatBackward>)

In [1]:
import numpy as np

In [2]:
test_array = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
test_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
test_array.shape

(2, 3)

In [5]:
test_array.ravel()

array([1, 2, 3, 4, 5, 6])

In [15]:
t = np.ones((3, 2, 3))

In [16]:
t[1] = 2
t[2] = 3

t[0, 0] = 1001
t[0, 1] = 1002

t[1, 0] = 2001
t[1, 1] = 2002

t[2, 0] = 3001
t[2, 1] = 3002

In [17]:
t

array([[[1001., 1001., 1001.],
        [1002., 1002., 1002.]],

       [[2001., 2001., 2001.],
        [2002., 2002., 2002.]],

       [[3001., 3001., 3001.],
        [3002., 3002., 3002.]]])

In [18]:
t.reshape(t.shape[0], -1)

array([[1001., 1001., 1001., 1002., 1002., 1002.],
       [2001., 2001., 2001., 2002., 2002., 2002.],
       [3001., 3001., 3001., 3002., 3002., 3002.]])

array([1., 1., 1.])

In [24]:
state = torch.zeros((4, 8))

In [25]:
action = torch.ones((4, 4))

In [28]:
action

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
torch.cat((state, action), dim=1)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1.]])

In [14]:
# contigoous behavior
a = torch.rand((4,))
b = torch.rand((4,))
c = torch.rand((4, 3, 2))

In [9]:
a.is_contiguous(), b.is_contiguous(), c.is_contiguous()

(True, True, True)

In [10]:
d = torch.cat((a, c.view(-1)))

In [11]:
d.is_contiguous()

True

In [16]:
c.view(4, -1).is_contiguous()

True