In [1]:
import itertools
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
m1 = nn.Linear(1, 1, bias=False)
m2 = nn.Linear(1, 1, bias=False)

In [3]:
nn.init.constant_(m1.weight, 5)
# nn.init.zeros_(m1.bias)
nn.init.constant_(m2.weight, 5)
# nn.init.zeros_(m2.bias)

Parameter containing:
tensor([[5.]], requires_grad=True)

In [4]:
for name, param in m1.named_parameters():
    print(f'Param name: {name}')
    print(param.data)

Param name: weight
tensor([[5.]])


In [5]:
for name, param in m2.named_parameters():
    print(f'Param name: {name}')
    print(param.data)

Param name: weight
tensor([[5.]])


In [6]:
# m1.eval()

In [7]:
optimizer = optim.SGD(itertools.chain(m1.parameters(), m2.parameters()), lr=1)

In [8]:
dummy = torch.tensor([1.])

In [9]:
with torch.set_grad_enabled(False):
    out = m1(dummy)
out, out.requires_grad

(tensor([5.]), False)

In [10]:
out = F.relu(out)
out = m2(out)
out, out.requires_grad

(tensor([25.], grad_fn=<SqueezeBackward3>), True)

In [11]:
loss = torch.zeros(1) - out
loss

tensor([-25.], grad_fn=<SubBackward0>)

In [12]:
loss.backward()
optimizer.step()

In [13]:
for name, param in m1.named_parameters():
    print(f'Param name: {name}')
    print(param.data)

Param name: weight
tensor([[5.]])


In [14]:
for name, param in m2.named_parameters():
    print(f'Param name: {name}')
    print(param.data)

Param name: weight
tensor([[10.]])


In [15]:
dummy2 = torch.tensor([1.])
m2(m1(dummy2))

tensor([50.], grad_fn=<SqueezeBackward3>)